export const Types = {
    SET_DEMOGRAPHICS: 'SET_DEMOGRAPHICS',
    SET_PLAN: 'SET_PLAN',
    SET_BILLING: 'SET_BILLING',
    SET_ADDON: 'SET_ADDON',
    REMOVE_ADDON: 'REMOVE_ADDON',
    INCREASE_STEP: 'INCREASE_STEP',
    DECREASE_STEP: 'DECREASE_STEP'
}